services:
  gemfile:
    working_dir: /srv/jekyll
    image: ruby:3.0
    command: ["bundle", "install"]
    volumes:
      - .:/srv/jekyll
  dev:
    container_name: blog
    build:
      context: .
      dockerfile: Dockerfile
    command: ["jekyll", "serve", "-l"]
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll